auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listing/<int:pk>", views.listing, name="listing"),
    path("listing/create", views.create_listing_view, name="createListing"),
    path("watchlist/", views.watchlist, name="watchlist"),
    path("watchlist/<int:pk>", views.watchlist_edit, name="watchlist"),
    path("category/<int:pk>", views.category, name="category"),
    path("listingstatus/<int:pk>", views.listing_status, name="listingStatus"),
    path("comment/<int:pk>", views.comment, name="comment"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.deletion import CASCADE


class Listing(models.Model):
    creator = models.ForeignKey('User', on_delete=CASCADE)
    categories = models.ForeignKey('Categories', on_delete=CASCADE, blank=True, null=True)
    name = models.CharField(max_length=75, blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    image = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True)
    current_price = models.ForeignKey("Bid", blank=True, null=True, on_delete=CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)


    def __str__(self):
        return self.name


class User(AbstractUser):
    pass
    

class Categories(models.Model):
    title = models.CharField(max_length=75)
    
    def __str__(self):
        return self.title


class Bid(models.Model):
    name = models.ForeignKey("Listing", on_delete=CASCADE)
    bidder = models.ForeignKey("User", on_delete=CASCADE, null=True)
    price = models.FloatField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} {self.price}"


class Watchlist(models.Model):
    user = models.ForeignKey("User", on_delete=CASCADE, null=True)
    listings = models.ForeignKey("Listing", null=True, blank=True, on_delete=CASCADE)

    def __str__(self):
        return f"{self.user} -- {self.listings}"


class Comment(models.Model):
    user = models.ForeignKey("User", on_delete=CASCADE, null=True)
    listing = models.ForeignKey("Listing", null=True, blank=True, on_delete=CASCADE)
    comment = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}"

auctions/forms.py
from django import forms
from .models import Categories

class CreateListingForm(forms.Form):
    name = forms.CharField(label='Title', max_length=100)
    categories = forms.ModelChoiceField(queryset=Categories.objects.all())
    price = forms.DecimalField(label='Price')
    image = forms.URLField(label='Image Url', required=False)
    description = forms.CharField(label="Description", widget=forms.Textarea)

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Max
from django.template import RequestContext

from .models import Bid, Categories, Comment, Listing, User, Watchlist
from .forms import CreateListingForm


def index(request):
    listings = Listing.objects.filter(is_active=True)

    # categories
    categories = Categories.objects.all()


    # cari watchlist yang ada pada user
    watchlist_list = []
    if request.user.username:
        watchlist = Watchlist.objects.filter(user = request.user)
        for w in watchlist:
            watchlist_list.append(w.listings)


    return render(request, "auctions/index.html", {
        "listings": listings,
        "wachlist": watchlist_list,
        "categories": categories
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")



def listing(request, pk):
    if request.method == "POST":
        # get the highest bid
        highest_bid = Bid.objects.filter(name=pk).aggregate(Max('price')).get('price__max')
        

        name = Listing.objects.get(id=request.POST["id_listing"])
        price = float(request.POST["bid"])
        bidder = request.user
        

        if highest_bid is not None and price < highest_bid or price < name.price:
            return HttpResponse("Error : price has been updated, your bidder is below current price")
        else:
            b = Bid(name=name, price=price, bidder=bidder)
            b.save()
    
            # update curent price
            # filter name and get the highest
            highest_bid = Bid.objects.filter(name=pk).aggregate(Max('price')).get('price__max')
            bid_instance = Bid.objects.filter(name=pk, price=highest_bid).order_by('created_at').first()
            l = Listing.objects.get(id=pk)
            l.current_price = bid_instance
            l.save()

            # print(latest_bidder)

            return redirect(f'/listing/{pk}')

    

    listing = Listing.objects.get(id=pk)

    # get the winner
    winner = Bid.objects.filter(listing=listing).first()
    print(winner)

    # get all bid from current listing
    bid = Bid.objects.filter(name=listing)

    # cek apakah listing tersebut ada di dalam watchlist
    watchlist = False
    if request.user.username:
        if Watchlist.objects.filter(listings=listing, user=request.user).exists():
            watchlist = True

    # get all comments in current listing
    comments = Comment.objects.filter(listing=pk)

    return render(request, "auctions/listing.html", {
        "pk":pk,
        "listing": listing,
        "watchlist": watchlist,
        "bid": bid,
        "comments": comments,
        "winner": winner

    })

@login_required
def create_listing_view(request):

    if request.method == "POST":
        form = CreateListingForm(request.POST)

        if form.is_valid():
            creator = request.user
            categories = form.cleaned_data['categories']
            name = form.cleaned_data['name']
            price = form.cleaned_data['price']
            image = form.cleaned_data['image']
            description = form.cleaned_data['description']

            l = Listing(creator=creator, categories=categories, name=name, price=price, image=image, description=description)
            l.save()
            return HttpResponseRedirect(reverse("index"))

    else:
        form = CreateListingForm()

    return render(request, "auctions/create.html", {
        "categories": Categories.objects.all(),
        "form": form
    })

def watchlist(request):
    listings = Listing.objects.all()
    
    # cari watchlist yang ada pada user
    watchlist_list = []
    if request.user.username:
        watchlist = Watchlist.objects.filter(user = request.user)
        for w in watchlist:
            watchlist_list.append(w.listings)

    return render(request, "auctions/watchlist.html", {
        "listings": listings,
        "wachlist": watchlist_list
    })




def watchlist_edit(request, pk):
    if request.method == "POST":
        instruction = request.POST["instruction"]
        listing = Listing.objects.get(id=pk)

        # add into db
        if instruction == "add":
            w = Watchlist(user = request.user, listings = listing)
            w.save()
            print("added")
        else:
            w = Watchlist.objects.get(user = request.user, listings=listing)
            w.delete()
            print("deleted")

    return redirect(f'/listing/{pk}')


def category(request, pk):

    listings = Listing.objects.filter(categories=pk)
    category_name = Categories.objects.get(id=pk)
    categories = Categories.objects.all()

    # cari watchlist yang ada pada user
    watchlist_list = []
    if request.user.username:
        watchlist = Watchlist.objects.filter(user = request.user)
        for w in watchlist:
            watchlist_list.append(w.listings)


    return render(request, "auctions/category.html", {
        "listings" : listings,
        "category_name" : category_name,
        "categories": categories,
        "wachlist": watchlist_list
    })


def listing_status(request, pk):

    if request.method == "POST":
        if request.POST["instruction"] == "close":
            Listing.objects.filter(id=pk).update(is_active=False)
        else:
            Listing.objects.filter(id=pk).update(is_active=True)

    return redirect(f'/listing/{pk}')
        

def comment(request, pk):

    if request.method == "POST":
        comment = request.POST["comment"]
        listing = Listing.objects.get(id=pk)
        c = Comment(comment=comment, user=request.user, listing=listing)
        c.save()
        return redirect(f'/listing/{pk}')
    
    return redirect(f'/listing/{pk}')

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}
{% load humanize %}

{% block body %}

<h2>All Listing in : {{category_name}}</h2>

<!-- categories -->
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Categories
    </button>
    <div class="dropdown-menu">
        {% for category in categories %}
            {% if category == category_name %}
                <a class="dropdown-item disabled" href="{% url 'category' category.id %}">{{category}}</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'category' category.id %}">{{category}}</a>

            {% endif %}

        {% endfor %}
    </div>
</div>
<!-- end of categories -->

    <div class="d-flex flex-wrap justify-content-center">
        {% for listing in listings %}
        <div class="card mt-2 mr-2" style="width: 18rem;">
            {% if listing.image %}
            <img src="{{listing.image}}" class="card-img-top" alt="...">
            {% else %}
            <img src="https://st3.depositphotos.com/23594922/31822/v/600/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"> <a href="{% url 'listing' listing.id %}">{{listing.name}}</a>  
                    {% if listing in wachlist %}<i class="bi bi-star-fill"></i>{% endif %}
                    {% if not listing.is_active %} (Closed) {% endif %}
                </h5>
                        <strong>Highest Bid : 
                            {% if listing.current_price %}
                                ${{listing.current_price.price|floatformat:2|intcomma}}
                            {% else %}
                                no bidder
                            {% endif %}
                        </strong> <br>

                        <p>Initial Price : ${{listing.price|floatformat:2|intcomma}}</p>  

                  <p class="card-text">{{listing.description|truncatechars:80}}</p>
                  <small class="text-muted">Created : {{listing.created_at}}</small>
            </div>
        </div>             
        {% endfor %}
    </div>

{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create Listing</h2>

    <div class="create mt-4">
        <form action="{% url 'createListing' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" id="id_submit" value="Submit">
        </form>
    </div>



{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load humanize %}

{% block body %}

<h2>Active Listings</h2>

    <div class="d-flex flex-wrap justify-content-center">
        {% for listing in listings %}
        <div class="card mt-2 mr-2" style="width: 18rem;">
            <img src="{{listing.image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title"> <a href="{% url 'listing' listing.id %}">{{listing.name}}</a>  </h5>
                  
                        <strong>Highest Bid : 
                            {% if listing.current_price %}
                                ${{listing.current_price.price|floatformat:2|intcomma}}
                            {% else %}
                                no bidder
                            {% endif %}
                        </strong> <br>

                        <p>Initial Price : ${{listing.price|floatformat:2|intcomma}}</p>  

                  <p class="card-text">{{listing.description|truncatechars:80}}</p>
                  <small class="text-muted">Created : {{listing.created_at}}</small>
            </div>
        </div>             
        {% endfor %}
    </div>


{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <style>
            .card-img-top {
                width: 100%;
                height: 17vw;
                object-fit: cover;
            }

            .listing-image{
                max-width: 500px;
            }
        </style>
    </head>
    <body>

        <div class="container">

        

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <!-- <a class="navbar-brand" href="#">Auctions</a> -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'createListing' %}">Create Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out ({{ user.username }})</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        <!-- end of Navbar -->
        
        <hr>
        
        {% block body %}
        {% endblock %}
    </div>
        <!-- javascript untuk bootstrap -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script>
            $("#id_name").addClass("form-control")
            $("#id_price").addClass("form-control")
            $("#id_image").addClass("form-control")
            $("#id_categories").addClass("form-control")
            $("#id_description").addClass("form-control")
            $("#id_submit").addClass("btn btn-primary")
        </script>
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% load humanize %}
{% block body %}

    <h2>Listing : {{listing.name}}  {% if not listing.is_active %} (closed){% endif %}
        <form action="{% url 'watchlist' listing.id %}" method="post">
            {% csrf_token %}
            {% if watchlist %}
            <button type="submit" class="btn btn-danger" name="instruction" value="remove">Remove From Watchlist</button>
            {% else %}
                {% if user.username %}
                <button type="submit" class="btn btn-info" name="instruction" value="add">Add to Watchlist</button>
                {% endif %}
            {% endif %}
        </form>

    </h2>


    <div class="row">
        <div class="col-lg">
            {% if listing.image %}
            <img src="{{listing.image}}" class="listing-image" alt="...">
            {% else %}
            <img src="https://st3.depositphotos.com/23594922/31822/v/600/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg" class="card-img-top" alt="...">
            {% endif %}
            <!-- <img src="{{listing.image}}" class="img-fluid" alt="Responsive image"> -->
        </div>
        <div class="col-lg">
            <form action="{% url 'listingStatus' listing.id %}" method="POST">
                <p class="display-4" >
                    {% if listing.current_price %}
                            ${{listing.current_price.price|intcomma}}
                        {% else %}
                            ${{listing.price|intcomma}}
                    {% endif %}

                    {% if not listing.is_active %} 
                        
                        {% if user.id == winner.bidder.id %}
                        <br> Winner : you 
                        {% else %}

                        <br> Winner : {{winner.bidder}} 
                        {% endif %}
                    {% endif %}
            
                <!-- button for closing the auctions -->
                    {% csrf_token %}
                    {% if user.id == listing.creator.id %}
                    {% if listing.is_active %}
                        <button type="submit" class="btn btn-secondary" name="instruction" value="close">Close Listing</button>
                        {% else %}
                        <button type="submit" class="btn btn-success" name="instruction" value="open">Open Listing</button>
                    {% endif %}
                    {% endif %}
                </p>
            </form>
                   
            <p style="font-size: larger;"> Listed By : {{listing.creator}} on {{listing.created_at}}</p>
            <p style="font-size: larger;"> Category : {{listing.categories}}</p>
            <p style="font-size: larger;">Description : {{listing.description}}</p>
            

            {% if user.username and listing.is_active %}
            <div class="form-bid">
                <form action="" method="POST">
                    {%csrf_token%}
                    <input type="number" name="id_listing" value="{{listing.id}}" hidden>
                    <input type="number" name="bid" class="form-control" step="0.1" placeholder="Place Your Bid" min="{{listing.current_price.price|add:1}}" required>
                    <input type="submit" value="Place Bid" class="btn btn-primary mt-2">

                </form>
            </div>
            {% endif %}

        </div>
    </div>
<hr>
   <!-- Comments and history -->
   <ul class="nav nav-pills mb-3 mt-5" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Comments</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Bid History</a>
    </li>
  </ul>

  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <!-- comments here -->
        <ul class="list-group list-group-flush mb-3">
            {% for c in comments %}
            <li class="list-group-item">
               <strong>{{c.user}} :</strong> <br>
               <p>{{c.comment}}</p>
               <small>{{c.created_at}}</small>
            </li>
            {% endfor %}
        </ul>
        <!-- end of comments -->
        {% if user.username %}
        <form action="{% url 'comment' listing.id %}" method="POST">
            {% csrf_token %}
            <textarea name="comment" class="form-control"></textarea>
            <input type="submit" class="btn btn-info mt-1" value="Post comment">
        </form>
        {% endif %}
    </div>
    <div class="tab-pane fade mb-5" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Bidder</th>
                <th scope="col">Price</th>

            </tr>
            </thead>
            <tbody>
          {% for b in bid %}
              <tr>
                <th>{{b.created_at}}</th>
                <td>{{b.bidder}}</td>
                <td>{{b.price}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>

  </div>

    



{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}
{% load humanize %}

{% block body %}

<h2>Your Watchlist</h2>
    <div class="d-flex flex-wrap justify-content-center">
        {% for listing in listings %}
        {% if listing in wachlist %}
        <div class="card mt-2 mr-2" style="width: 18rem;">
            {% if listing.image %}
            <img src="{{listing.image}}" class="card-img-top" alt="...">
            {% else %}
            <img src="https://st3.depositphotos.com/23594922/31822/v/600/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"> <a href="{% url 'listing' listing.id %}">{{listing.name}}</a>  
                    {% if listing in wachlist %}<i class="bi bi-star-fill"></i>{% endif %}
                </h5>
                        <strong>Highest Bid : 
                            {% if listing.current_price %}
                                ${{listing.current_price.price|floatformat:2|intcomma}}
                            {% else %}
                                no bidder
                            {% endif %}
                        </strong> <br>

                        <p>Initial Price : ${{listing.price|floatformat:2|intcomma}}</p>  

                  <p class="card-text">{{listing.description|truncatechars:80}}</p>
                  <small class="text-muted">Created : {{listing.created_at}}</small>
            </div>
        </div>     
        {% endif %}        
        {% endfor %}
    </div>
{% endblock %}